import { Article } from './article';

export const ARTICLES: Article[] = [
    {
        id: 1,
        title: 'Primeiro artigo',
        content: '<p>Danish gingerbread candy canes dessert bear claw. Halvah sweet cotton candy bonbon cupcake jujubes cake sesame snaps pudding. Jelly beans chocolate ice cream brownie. Jelly-o biscuit tart topping pudding muffin sesame snaps pie lollipop. Biscuit bonbon wafer powder gummi bears pie marshmallow sugar plum.</p> <p>Dragée jelly cake. Bear claw carrot cake lollipop bear claw tart cake tart chocolate bar. Danish gummi bears soufflé ice cream. Pudding candy oat cake pie cupcake jelly cotton candy dessert gummies. Ice cream tootsie roll carrot cake powder carrot cake. Carrot cake marzipan chocolate bar wafer. Bonbon marshmallow caramels caramels liquorice. Croissant gingerbread sesame snaps pudding chocolate cake powder. Lollipop marshmallow halvah brownie candy canes sweet biscuit dragée powder.Dragée cupcake macaroon cake powder croissant. <p>Cookie oat cake cheesecake icing cheesecake. Pastry gummies caramels sweet.Cotton candy dragée brownie muffin sweet liquorice oat cake. Liquorice jelly beans gummies dragée chocolate candy. Pastry sesame snaps gummies donut halvah chupa chups wafer. Bear claw lemon drops apple pie. Bear claw brownie toffee. Bear claw dragée oat cake sugar plum tiramisu pudding powder donut candy canes. Sweet roll pie candy. Dragée pudding tiramisu sugar plum sweet. Wafer carrot cake powder.Sugar plum muffin jelly tart tiramisu tootsie roll cheesecake jujubes. Cookie brownie sesame snaps carrot cake toffee macaroon carrot cake macaroon fruitcake. Pastry biscuit apple pie. <p>Caramels sesame snaps pastry jelly-o candy canes gingerbread. Dessert dessert candy canes chupa chups powder. Cake cake candy canes jelly beans. Gummies lollipop cheesecake marshmallow gummies. Fruitcake brownie sugar plum candy canes. Macaroon muffin cookie gummies gummies sesame snaps candy canes tart.</p>Candy halvah macaroon lollipop donut soufflé. Sweet chocolate bar tootsie roll lollipop wafer sesame snaps bonbon. Lollipop candy bonbon cake tart brownie lollipop. Macaroon halvah brownie bear claw caramels croissant marshmallow gummi bears.</p>',
        description: "Meu primeiro artigo, leia :)",
        key: 'my-first-article',
        date: new Date(),
        imageUrl: 'https://www.memesmonkey.com/images/memesmonkey/55/550b4a066a04e332793a78d829ee04a7.jpeg'
    },
    {
        id: 2,
        title: 'Segundo artigo',
        content: '<p>Danish gingerbread candy canes dessert bear claw. Halvah sweet cotton candy bonbon cupcake jujubes cake sesame snaps pudding. Jelly beans chocolate ice cream brownie. Jelly-o biscuit tart topping pudding muffin sesame snaps pie lollipop. Biscuit bonbon wafer powder gummi bears pie marshmallow sugar plum.</p> <p>Dragée jelly cake. Bear claw carrot cake lollipop bear claw tart cake tart chocolate bar. Danish gummi bears soufflé ice cream. Pudding candy oat cake pie cupcake jelly cotton candy dessert gummies. Ice cream tootsie roll carrot cake powder carrot cake. Carrot cake marzipan chocolate bar wafer. Bonbon marshmallow caramels caramels liquorice. Croissant gingerbread sesame snaps pudding chocolate cake powder. Lollipop marshmallow halvah brownie candy canes sweet biscuit dragée powder.Dragée cupcake macaroon cake powder croissant. <p>Cookie oat cake cheesecake icing cheesecake. Pastry gummies caramels sweet.Cotton candy dragée brownie muffin sweet liquorice oat cake. Liquorice jelly beans gummies dragée chocolate candy. Pastry sesame snaps gummies donut halvah chupa chups wafer. Bear claw lemon drops apple pie. Bear claw brownie toffee. Bear claw dragée oat cake sugar plum tiramisu pudding powder donut candy canes. Sweet roll pie candy. Dragée pudding tiramisu sugar plum sweet. Wafer carrot cake powder.Sugar plum muffin jelly tart tiramisu tootsie roll cheesecake jujubes. Cookie brownie sesame snaps carrot cake toffee macaroon carrot cake macaroon fruitcake. Pastry biscuit apple pie. Caramels sesame snaps pastry jelly-o candy canes gingerbread. Dessert dessert candy canes chupa chups powder. Cake cake candy canes jelly beans. Gummies lollipop cheesecake marshmallow gummies. Fruitcake brownie sugar plum candy canes. Macaroon muffin cookie gummies gummies sesame snaps candy canes tart.</p>Candy halvah macaroon lollipop donut soufflé. Sweet chocolate bar tootsie roll lollipop wafer sesame snaps bonbon. Lollipop candy bonbon cake tart brownie lollipop. Macaroon halvah brownie bear claw caramels croissant marshmallow gummi bears.</p>',
        description: "Meu segundo artigo, leia :)",
        key: 'my-second-article',
        date: new Date(),
        imageUrl: 'https://i.pinimg.com/236x/d1/07/17/d107178c10a908b3ec8aae3082f6dd58.jpg'
    }
]